added articles infrastructure
Pull-Request-Community/pull-request-community-website pull request #142
Opened 2022-03-11 13:01 UTC by shmuelpro

2022-03-12 17:02 UTC, MichalPorag requested changes

2022-03-12 17:02 UTC, MichalPorag commented on package.json
> +    "marked": "^4.0.12",
Also, deploy failed, please fix.

2022-03-12 18:01 UTC, shmuelpro commented on package.json
> +    "marked": "^4.0.12",
> Why did you use marked and not just the options of markup lang?

I don;t understand, do we have a different package that converts markup to HTML?

2022-05-14 12:47 UTC, MichalPorag commented
@shmuelpro, Hi, how are you?
If you are too busy right now, please let me know so I can pass this task on to someone else.

2022-06-04 06:30 UTC, closed without merging