#171|Resolved|getting texts from json file
Pull-Request-Community/pull-request-community-website pull request #180
Opened 2022-05-23 15:22 UTC by bargalya

by new useTranslator instead of hard-coded text in html

2022-05-27 13:55 UTC, bargalya commented
Hi @MichalPorag can you please review? thanks :)

2022-05-28 13:18 UTC, MichalPorag requested changes
Great job! 
Please separate the text JSON into different files by modules

2022-06-09 05:46 UTC, bargalya commented
Hi @MichalPorag can you please review again? thanks :)

2022-06-10 10:32 UTC, MichalPorag approved these changes

2022-06-10 10:32 UTC, merged