Remove un needed style
Pull-Request-Community/pull-request-community-website pull request #218
Opened 2022-06-19 17:38 UTC by Noamili

2022-07-02 07:17 UTC, MichalPorag approved these changes
Great work! please fix conflicts

2022-07-02 07:25 UTC, MichalPorag approved these changes

2022-07-03 16:41 UTC, Noamili commented on styles/Home.module.scss
> +  margin: -24px auto 0 auto;
24 instead of 0

2022-07-03 16:51 UTC, MichalPorag requested changes
Great work! just a few comments

2022-07-03 16:51 UTC, MichalPorag commented on styles/Home.module.scss
>  @media screen and (max-width: 600px) {
please chang to 1280px

2022-07-03 16:51 UTC, MichalPorag commented on styles/Home.module.scss
> +    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
please remove tis

2022-07-03 16:51 UTC, MichalPorag commented on styles/Home.module.scss
> +  grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
Please change to 300px min

2022-07-09 13:35 UTC, MichalPorag approved these changes
Geat work!

2022-07-09 13:35 UTC, merged