Create YanivWeinshtein.json
Pull-Request-Community/pull-request-community-website pull request #267
Opened 2022-08-07 17:44 UTC by YanivWein24

Added my info in a new file in the 'people' directory

2022-08-07 20:25 UTC, rinaok approved these changes

2022-08-09 10:58 UTC, rinaok requested changes
@YanivWein24 There is one test that is failing

2022-08-09 12:29 UTC, YanivWein24 commented
> @YanivWein24 There is one test that is failing

I have changed the indentation in order to pass ESLint test

2022-08-09 13:24 UTC, rinaok approved these changes

2022-08-09 13:25 UTC, rinaok commented
> > @YanivWein24 There is one test that is failing
> 
> I have changed the indentation in order to pass ESLint test

approved

2022-09-09 13:56 UTC, merged